### ISSUE TITLE
Powerview hub Not detected by Homey pro.

### ISSUE THREAD

**Issue by QJoost** [martijnpoppen/homey_nl.luxaflex.powerview#10]
After succesfull Installation of Luxaflex Duette and Powerview hub and app, I am not able to get the hub in the devices section. 
what am I doing wrong here?

**Comment by martijnpoppen** [comment]
Hi
This is known and already is a fix available:

https://community.homey.app/t/app-pro-powerview-luxaflex-hunter-douglas/71319/76?u=martijnpoppen
