### ISSUE TITLE
Luxaflex powerview werkt niet in Homey app

### ISSUE THREAD

**Issue by WoonDecorGouda** [martijnpoppen/homey_nl.luxaflex.powerview#5]
Goedendag, 

Via Athom zijn we doorgestuurd om jouw de volgende vraag te stellen. 

We hebben een vraag over de communicatie tussen Homey en Luxaflex powerview. Als we de powerview app hebben aangesloten op de Homey dan kunnen we op de app alleen maar de aan/uit knop indrukken en er gebeurt niks.
We hebben in de powerview app 3 producten staan welke in de powerview app zelf wel werkt. Alleen werkt het dus nog niet via Homey. Graag horen we hoe we dit kunnen oplossen.

Mvg, WoonDecorGouda

**Comment by Jdegroot1** [comment]
Hallo,

Ik ben niet de ontwikkelaar maar ook gewoon een gebruiker. Via homey kan je niet direct de luxaflex aansturen. Homey kan enkel een scene activeren. 

Ik heb bijvoorbeeld een scene in de luxaflex app met avond. Dan kan ik via homey een flow maken die de scene activeert om een bepaalde tijd met bepaalde voorwaarden.

**Comment by Dqsp** [comment]
Maar om een flow te maken moet je de scènes toch kunnen zien? Zie alleen de hub (gen2). Vindt nergens terug waar je de scènes kunt overhalen.

**Comment by martijnpoppen** [comment]
Closed due to new developer since 28-10-2022.
