### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by Tweaqer** [martijnpoppen/homey_nl.luxaflex.powerview#7]
Report id: 2c7cb861-3eb7-4459-8bd8-d7acdc28bd41

Flows don't work anymore. They appear to be running but the curtains don't move. The official Luxaflex app on Android and iOS still works without problems though.
Also the scenes can't be collected neither so my guess is that the connection with the hub is lost?

**Comment by martijnpoppen** [comment]
Closed due to new developer since 28-10-2022.
